apiVersion: v1
kind: Service
metadata:
  name: productpage-external
  labels:
    app: productpage
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9080
  selector:
    app: productpage
